// Phase 1 placeholder. The real seed (~30 suppliers, ~80 contracts, clauses, consents,
// regions, policy-decision provenance) is generated by data/synthetic/generate.py in
// Phase 2 and overwrites this file (spec §5.2).
CREATE CONSTRAINT supplier_id IF NOT EXISTS FOR (s:Supplier) REQUIRE s.id IS UNIQUE;
